{% set name = "odrpack" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/odrpack-{{ version }}.tar.gz
  sha256: 5a9dc4b0964a2c26fd4dd723e89139ea27db457309306179cb6009133887ad29

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [python != "3.12" or unix or osx or python_impl == "pypy"]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - m2w64-gcc-fortran  # [win]     # gfortran on Windows
    - m2w64-gcc          # [win]
    - pkg-config
  host:
    - python
    - pip
    - meson-python >=0.15.0
    - openblas
  run:
    - python
    - numpy >=1.24
    - libopenblas 

test:
  imports:
    - odrpack
  source_files:
    - tests
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - scipy

about:
  home: https://github.com/HugoMVale/odrpack-python
  summary: Package for weighted orthogonal distance regression (ODR).
  license: MIT
  license_file: LICENSE
  doc_url: https://hugomvale.github.io/odrpack-python/

extra:
  recipe-maintainers:
    - HugoMVale
