{% set name = "odrpack" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/odrpack-{{ version }}.tar.gz
  sha256: 0898475969cf4119a340879b99f632ffd9fbe1c88fdcbeea62eeb91fba1cda70

build:
  number: 0
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - pkg-config
    - ninja
    - python                               # [build_platform != target_platform]
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
    - clang                                # [win]    
  host:
    - python
    - pip
    - meson-python >=0.15.0
    - openblas
  run:
    - python
    - numpy >=1.24
    - libopenblas

test:
  imports:
    - odrpack
  source_files:
    - tests
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest
    - scipy

about:
  home: https://github.com/HugoMVale/odrpack-python
  summary: Package for weighted orthogonal distance regression (ODR).
  license: MIT
  license_file: LICENSE
  doc_url: https://hugomvale.github.io/odrpack-python/

extra:
  recipe-maintainers:
    - HugoMVale
